[tool.poetry]
name = "qalgo"
version = "0.1.0"
description = ""
authors = ["Adi Salimgereev <adi.salimgereev25@fizmat.kz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
